## 2.1 Elementwise operations

In [1]:
import numpy as np

In [24]:
# basic ops
# scalar
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [4]:
a + 1

array([2, 3, 4, 5])

In [6]:
2 ** a

array([ 2,  4,  8, 16])

In [7]:
a ** 2

array([ 1,  4,  9, 16])

In [11]:
# elementwise
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [12]:
a - b

array([-1.,  0.,  1.,  2.])

In [13]:
a * b

array([2., 4., 6., 8.])

In [28]:
j = np.arange(5)
j

array([0, 1, 2, 3, 4])

In [29]:
2 ** (j + 1) - j 

array([ 2,  3,  6, 13, 28])

In [18]:
a = np.arange(10000)

In [19]:
%timeit a + 1

13.3 µs ± 244 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
l = range(10000)
%timeit [i+1 for i in l]

1.32 ms ± 3.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
c * c # not matrix multiplication

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# matrix multiplication
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [33]:
# execises
a = np.ones(5) + 1
a

array([2., 2., 2., 2., 2.])

In [35]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [37]:
a ** b

array([ 1.,  2.,  4.,  8., 16.])

In [40]:
# comparisons
# element-wise
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [41]:
a > b

array([False, False,  True, False])

In [42]:
# array-wise
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a, b)

False

In [43]:
np.array_equal(a, c)

True

In [44]:
# logical ops
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [45]:
np.logical_and(a, b)

array([ True, False, False, False])

In [47]:
# transcendental
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [49]:
np.log(a)

/home/kcsz/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [50]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [51]:
# shape mismatches
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [59]:
# transposition
a = np.triu(np.ones((3, 3)), 1)
a

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [63]:
a.T

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [64]:
b = np.tril(np.ones((3, 3)))
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [66]:
np.allclose(a, b)

False

In [67]:
np.allclose?